### ISSUE TITLE
Remove vendor folder

### ISSUE THREAD

**Issue by bahlo** [blend/action-composite#2]
Hey, thanks for that action, this is super useful! 

I'm a bit worried about the vendor folder though as it's hard to audit. With go modules and GOSUMDB it should not be necessary, should it?

**Comment by dhermes** [comment]
`go mod` will validate `vendor/` against the contents of `go.sum`, so you get the same level of audit you would without it. Note that `go mod vendor` is how the directory is generated (i.e. this is part of a `go mod`-native workflow). The goal here is to (A) enable "airplane mode" dev after first clone and (B) make actual dependency changes be part of code reviews as diffs.

I am going to pre-emptively close this issue since I hope I've assuaged your concerns. We're happy to re-open the issue though if you think there is more discussion to be had.
